[package]
name = "ripasso"
version = "0.0.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com"]

[features]
default = ["qml"]
use-gtk = ["gtk"]
use-qml = ["qml"]
use-tui = ["cursive"]

[dependencies]
gtk = { version = "0.3.0", features = ["v3_10"], optional = true }
qml = { git = "https://github.com/White-Oak/qml-rust", optional = true }
cursive = { version = "0.7.5", optional = true }
glib = "0.4.0"
notify = "4.0.2"
glob = "0.2.11"
clipboard =  "0.4.2"
gpgme = { version = "0.6.1", "default-features" = false }
